// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/tokenplay/tokenplay.proto

package tokenplay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tokenplay service

type TokenplayService interface {
	AddWord(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Tokenplay_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Tokenplay_PingPongService, error)
}

type tokenplayService struct {
	c    client.Client
	name string
}

func NewTokenplayService(name string, c client.Client) TokenplayService {
	return &tokenplayService{
		c:    c,
		name: name,
	}
}

func (c *tokenplayService) AddWord(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Tokenplay.AddWord", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenplayService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Tokenplay_StreamService, error) {
	req := c.c.NewRequest(c.name, "Tokenplay.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &tokenplayServiceStream{stream}, nil
}

type Tokenplay_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type tokenplayServiceStream struct {
	stream client.Stream
}

func (x *tokenplayServiceStream) Close() error {
	return x.stream.Close()
}

func (x *tokenplayServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tokenplayServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tokenplayServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tokenplayServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tokenplayService) PingPong(ctx context.Context, opts ...client.CallOption) (Tokenplay_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Tokenplay.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &tokenplayServicePingPong{stream}, nil
}

type Tokenplay_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type tokenplayServicePingPong struct {
	stream client.Stream
}

func (x *tokenplayServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *tokenplayServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *tokenplayServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tokenplayServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tokenplayServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *tokenplayServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Tokenplay service

type TokenplayHandler interface {
	AddWord(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Tokenplay_StreamStream) error
	PingPong(context.Context, Tokenplay_PingPongStream) error
}

func RegisterTokenplayHandler(s server.Server, hdlr TokenplayHandler, opts ...server.HandlerOption) error {
	type tokenplay interface {
		AddWord(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Tokenplay struct {
		tokenplay
	}
	h := &tokenplayHandler{hdlr}
	return s.Handle(s.NewHandler(&Tokenplay{h}, opts...))
}

type tokenplayHandler struct {
	TokenplayHandler
}

func (h *tokenplayHandler) AddWord(ctx context.Context, in *Request, out *Response) error {
	return h.TokenplayHandler.AddWord(ctx, in, out)
}

func (h *tokenplayHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TokenplayHandler.Stream(ctx, m, &tokenplayStreamStream{stream})
}

type Tokenplay_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type tokenplayStreamStream struct {
	stream server.Stream
}

func (x *tokenplayStreamStream) Close() error {
	return x.stream.Close()
}

func (x *tokenplayStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tokenplayStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tokenplayStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tokenplayStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *tokenplayHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TokenplayHandler.PingPong(ctx, &tokenplayPingPongStream{stream})
}

type Tokenplay_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type tokenplayPingPongStream struct {
	stream server.Stream
}

func (x *tokenplayPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *tokenplayPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *tokenplayPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *tokenplayPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *tokenplayPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *tokenplayPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
